package main

import (
	"fmt"
	"sort"
	"strings"
)

// capExpr renders a .klc Cap-column value (a bitmask of CAPLOK=1,
// SGCAPS=2, CAPLOKALTGR=4) as a readable C expression.
func capExpr(cap int) string {
	if cap == 0 {
		return "0"
	}
	var parts []string
	if cap&0x01 != 0 {
		parts = append(parts, "CAPLOK")
	}
	if cap&0x02 != 0 {
		parts = append(parts, "SGCAPS")
	}
	if cap&0x04 != 0 {
		parts = append(parts, "CAPLOKALTGR")
	}
	if len(parts) == 0 {
		return fmt.Sprintf("0x%02x", cap)
	}
	return strings.Join(parts, " | ")
}

// valueExpr renders one character cell as a C expression.
func valueExpr(v Value) string {
	if v.None {
		return "WCH_NONE"
	}
	if v.Rune < 0x80 {
		switch v.Rune {
		case '\'', '\\':
			return fmt.Sprintf("'\\%c'", v.Rune)
		case '\b':
			return "'\\b'"
		case '\t':
			return "'\\t'"
		case '\r':
			return "'\\r'"
		case '\n':
			return "'\\n'"
		}
		if v.Rune >= 0x20 && v.Rune < 0x7f {
			return fmt.Sprintf("'%c'", v.Rune)
		}
	}
	return fmt.Sprintf("0x%04x", v.Rune)
}

// buildModifiers computes the MODIFIERS.ModNumber[] array from the .klc's
// declared SHIFTSTATE list: each declared raw bitmask value maps to its
// position in that list; every other combination (up to the next power of
// two covering the highest declared value) is SHFT_INVALID.
func buildModifiers(states []int) (size int, modNumbers []string) {
	maxState := 0
	for _, s := range states {
		if s > maxState {
			maxState = s
		}
	}
	size = 1
	for size <= maxState {
		size *= 2
	}
	modNumbers = make([]string, size)
	for i := range modNumbers {
		modNumbers[i] = "SHFT_INVALID"
	}
	for idx, s := range states {
		modNumbers[s] = fmt.Sprintf("%d", idx)
	}
	return size, modNumbers
}

// resolvedVK is ausVK[]'s value for one scancode, with the row that
// produced it (if any) for error messages.
type resolvedVK struct {
	Expr string
	Row  *Row
}

// buildAusVK starts from the standard base table and overrides scancodes
// that the .klc's LAYOUT section explicitly defines.
func buildAusVK(rows []Row) (map[byte]resolvedVK, error) {
	table := make(map[byte]resolvedVK, len(ausVKBase))
	for sc, e := range ausVKBase {
		table[sc] = resolvedVK{Expr: e.VK + e.Flags}
	}
	for i := range rows {
		r := &rows[i]
		expr, err := vkExprFor(r.VKName)
		if err != nil {
			return nil, fmt.Errorf("line %d: %w", r.Line, err)
		}
		if r.ScanCode > maxScanCode {
			return nil, fmt.Errorf("line %d: scancode 0x%02x is beyond the supported range (0x00-0x%02x)", r.Line, r.ScanCode, maxScanCode)
		}
		table[r.ScanCode] = resolvedVK{Expr: expr, Row: r}
	}
	return table, nil
}

// Generate renders the complete kbd*.c source for the given layout.
func Generate(l *Layout) (string, error) {
	numStates := len(l.ShiftStates)

	ausVK, err := buildAusVK(l.Rows)
	if err != nil {
		return "", err
	}

	modSize, modNumbers := buildModifiers(l.ShiftStates)

	// Split LAYOUT rows into "simple" (base+shift only) and "extended"
	// (needs every declared shift state) character tables.
	var simpleRows, extendedRows []Row
	for _, r := range l.Rows {
		needsExtended := false
		for i := 2; i < len(r.Values); i++ {
			if !r.Values[i].None {
				needsExtended = true
				break
			}
		}
		if needsExtended {
			extendedRows = append(extendedRows, r)
		} else {
			simpleRows = append(simpleRows, r)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "/***************************************************************************\\\n")
	fmt.Fprintf(&b, "* Module Name: %s.C\n", strings.ToUpper(l.Name))
	fmt.Fprintf(&b, "*\n* %s\n", l.Description)
	fmt.Fprintf(&b, "*\n* Generated by klc2c from a .klc source. Do not edit by hand -\n")
	fmt.Fprintf(&b, "* edit the .klc and regenerate instead.\n")
	fmt.Fprintf(&b, "\\***************************************************************************/\n\n")
	fmt.Fprintf(&b, "#include <windows.h>\n#include \"kbd.h\"\n\n")

	// ausVK[]
	fmt.Fprintf(&b, "static USHORT ausVK[] = {\n")
	for sc := byte(0); ; sc++ {
		e := ausVK[sc]
		fmt.Fprintf(&b, "    /* %02X */ %s,\n", sc, e.Expr)
		if sc == maxScanCode {
			break
		}
	}
	fmt.Fprintf(&b, "};\n\n")

	// aE0VscToVk[] / aE1VscToVk[]
	fmt.Fprintf(&b, "static VSC_VK aE0VscToVk[] = {\n")
	for _, e := range aE0VscToVkBase {
		fmt.Fprintf(&b, "    { 0x%02X, %s | KBDEXT },\n", e.ScanCode, e.VK)
	}
	fmt.Fprintf(&b, "    { 0, 0 }\n};\n\n")

	fmt.Fprintf(&b, "static VSC_VK aE1VscToVk[] = {\n")
	for _, e := range aE1VscToVkBase {
		fmt.Fprintf(&b, "    { 0x%02X, %s },\n", e.ScanCode, e.VK)
	}
	fmt.Fprintf(&b, "    { 0, 0 }\n};\n\n")

	// aVkToBits[] / CharModifiers
	fmt.Fprintf(&b, "static VK_TO_BIT aVkToBits[] = {\n")
	fmt.Fprintf(&b, "    { VK_SHIFT,   KBDSHIFT },\n")
	fmt.Fprintf(&b, "    { VK_CONTROL, KBDCTRL  },\n")
	fmt.Fprintf(&b, "    { VK_MENU,    KBDALT   },\n")
	fmt.Fprintf(&b, "    { 0,          0        }\n};\n\n")

	fmt.Fprintf(&b, "static MODIFIERS CharModifiers = {\n")
	fmt.Fprintf(&b, "    &aVkToBits[0],\n    %d,\n    {\n", modSize-1)
	for i, mn := range modNumbers {
		comma := ","
		if i == len(modNumbers)-1 {
			comma = ""
		}
		fmt.Fprintf(&b, "        %s%s\n", mn, comma)
	}
	fmt.Fprintf(&b, "    }\n};\n\n")

	// aVkToWch2[] (simple rows: base + shift only)
	fmt.Fprintf(&b, "static VK_TO_WCHARS2 aVkToWch2[] = {\n")
	for _, r := range simpleRows {
		expr, _ := vkExprFor(r.VKName)
		fmt.Fprintf(&b, "  { %-14s, %-11s, %s, %s },\n",
			expr, capExpr(r.Cap), valueExpr(r.Values[0]), valueExpr(r.Values[1]))
	}
	fmt.Fprintf(&b, "  { 0, 0, 0, 0 }\n};\n\n")

	// aVkToWch<N>[] (extended rows: every declared shift state)
	extName := fmt.Sprintf("aVkToWch%d", numStates)
	extType := fmt.Sprintf("VK_TO_WCHARS%d", numStates)
	if len(extendedRows) > 0 {
		fmt.Fprintf(&b, "static %s %s[] = {\n", extType, extName)
		for _, r := range extendedRows {
			expr, _ := vkExprFor(r.VKName)
			var cells []string
			for _, v := range r.Values {
				cells = append(cells, valueExpr(v))
			}
			fmt.Fprintf(&b, "  { %-14s, %-11s, %s },\n", expr, capExpr(r.Cap), strings.Join(cells, ", "))
		}
		zeros := make([]string, numStates)
		for i := range zeros {
			zeros[i] = "0"
		}
		fmt.Fprintf(&b, "  { 0, 0, %s }\n};\n\n", strings.Join(zeros, ", "))
	}

	// aVkToWch1[] - numpad digits (fixed, not klc-customizable)
	fmt.Fprintf(&b, "static VK_TO_WCHARS1 aVkToWch1[] = {\n")
	for d := 0; d <= 9; d++ {
		fmt.Fprintf(&b, "    { VK_NUMPAD%d, 0, '%d' },\n", d, d)
	}
	fmt.Fprintf(&b, "    { 0, 0, '\\0' }\n};\n\n")

	fmt.Fprintf(&b, "static VK_TO_WCHAR_TABLE aVkToWcharTable[] = {\n")
	if len(extendedRows) > 0 {
		fmt.Fprintf(&b, "    { (PVK_TO_WCHARS1)%s, %d, sizeof(%s[0]) },\n", extName, numStates, extName)
	}
	fmt.Fprintf(&b, "    { (PVK_TO_WCHARS1)aVkToWch2, 2, sizeof(aVkToWch2[0]) },\n")
	fmt.Fprintf(&b, "    { (PVK_TO_WCHARS1)aVkToWch1, 1, sizeof(aVkToWch1[0]) },\n")
	fmt.Fprintf(&b, "    { NULL, 0, 0 }\n};\n\n")

	// aKeyNames[] / aKeyNamesExt[]
	writeKeyNames := func(name string, entries []KeyName) {
		fmt.Fprintf(&b, "static VSC_LPWSTR %s[] = {\n", name)
		sorted := append([]KeyName(nil), entries...)
		sort.Slice(sorted, func(i, j int) bool { return sorted[i].ScanCode < sorted[j].ScanCode })
		for _, kn := range sorted {
			fmt.Fprintf(&b, "    0x%02x, L\"%s\",\n", kn.ScanCode, kn.Name)
		}
		fmt.Fprintf(&b, "    0, NULL\n};\n\n")
	}
	writeKeyNames("aKeyNames", l.KeyNames)
	writeKeyNames("aKeyNamesExt", l.KeyNamesExt)

	// KBDTABLES + KbdLayerDescriptor
	fmt.Fprintf(&b, "static KBDTABLES KbdTables = {\n")
	fmt.Fprintf(&b, "    &CharModifiers,\n    aVkToWcharTable,\n    NULL,\n")
	fmt.Fprintf(&b, "    aKeyNames,\n    aKeyNamesExt,\n    NULL,\n")
	fmt.Fprintf(&b, "    ausVK,\n    sizeof(ausVK) / sizeof(ausVK[0]),\n")
	fmt.Fprintf(&b, "    aE0VscToVk,\n    aE1VscToVk,\n")
	fmt.Fprintf(&b, "    0,\n    0,\n    0,\n    NULL,\n    0,\n    0\n};\n\n")
	fmt.Fprintf(&b, "PKBDTABLES KbdLayerDescriptor(VOID)\n{\n    return &KbdTables;\n}\n")

	return b.String(), nil
}

// GenerateDef renders the matching .def export file.
func GenerateDef(l *Layout) string {
	return fmt.Sprintf("LIBRARY %s\n\nEXPORTS\n    KbdLayerDescriptor @1\n", strings.ToUpper(l.Name))
}
